/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ACard: (typeof import('ant-design-vue/es'))['Card']
    ACol: (typeof import('ant-design-vue/es'))['Col']
    AConfigProvider: (typeof import('ant-design-vue/es'))['ConfigProvider']
    ADescriptions: (typeof import('ant-design-vue/es'))['Descriptions']
    ADescriptionsItem: (typeof import('ant-design-vue/es'))['DescriptionsItem']
    ADropdown: (typeof import('ant-design-vue/es'))['Dropdown']
    ALayout: (typeof import('ant-design-vue/es'))['Layout']
    ALayoutContent: (typeof import('ant-design-vue/es'))['LayoutContent']
    ALayoutFooter: (typeof import('ant-design-vue/es'))['LayoutFooter']
    ALayoutHeader: (typeof import('ant-design-vue/es'))['LayoutHeader']
    ALayoutSider: (typeof import('ant-design-vue/es'))['LayoutSider']
    AMenu: (typeof import('ant-design-vue/es'))['Menu']
    AMenuItem: (typeof import('ant-design-vue/es'))['MenuItem']
    APageHeader: (typeof import('ant-design-vue/es'))['PageHeader']
    ARow: (typeof import('ant-design-vue/es'))['Row']
    ASubMenu: (typeof import('ant-design-vue/es'))['SubMenu']
    ATag: (typeof import('ant-design-vue/es'))['Tag']
    ChildMenu: (typeof import('./../components/layouts/components/ChildMenu.vue'))['default']
    CloudAside: (typeof import('./../components/layouts/components/CloudAside.vue'))['default']
    CloudFooter: (typeof import('./../components/layouts/components/CloudFooter.vue'))['default']
    CloudHeader: (typeof import('./../components/layouts/components/CloudHeader.vue'))['default']
    CloudLayout: (typeof import('./../components/layouts/CloudLayout.vue'))['default']
    CommonLayout: (typeof import('./../components/layouts/CommonLayout.vue'))['default']
    FiveHundred: (typeof import('./../components/ErrorMessage/FiveHundred.vue'))['default']
    FourFour: (typeof import('./../components/ErrorMessage/FourFour.vue'))['default']
    FourThree: (typeof import('./../components/ErrorMessage/FourThree.vue'))['default']
    HeaderTitle: (typeof import('./../components/CommonView/HeaderTitle.vue'))['default']
    HelloWorld: (typeof import('./../components/HelloWorld.vue'))['default']
    IconCommunity: (typeof import('./../components/icons/IconCommunity.vue'))['default']
    IconDocumentation: (typeof import('./../components/icons/IconDocumentation.vue'))['default']
    IconEcosystem: (typeof import('./../components/icons/IconEcosystem.vue'))['default']
    IconSupport: (typeof import('./../components/icons/IconSupport.vue'))['default']
    IconTooling: (typeof import('./../components/icons/IconTooling.vue'))['default']
    MonacoEditor: (typeof import('./../components/EditorView/MonacoEditor.vue'))['default']
    PageWrapper: (typeof import('./../components/Page/src/PageWrapper.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
    SvgIcon: (typeof import('./../components/SvgIcon/SvgIcon.vue'))['default']
    TheWelcome: (typeof import('./../components/TheWelcome.vue'))['default']
    WelcomeItem: (typeof import('./../components/WelcomeItem.vue'))['default']
  }
}
